In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
vocb_size = 10000

In [25]:
#one hot representation
onehot_repr=[one_hot(words,vocb_size)for words in sent] 
print(onehot_repr)


[[1107, 5553, 7443, 9630], [1107, 5553, 7443, 7038], [1107, 7, 7443, 2616], [443, 6832, 9112, 3877, 1147], [443, 6832, 9112, 3877, 1533], [5710, 1107, 3213, 7443, 2928], [6988, 6347, 6825, 3877]]


In [26]:
#Word Embedding Represntation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [27]:
sent_height = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_height)
print(embedded_docs)

[[   0    0    0    0 1107 5553 7443 9630]
 [   0    0    0    0 1107 5553 7443 7038]
 [   0    0    0    0 1107    7 7443 2616]
 [   0    0    0  443 6832 9112 3877 1147]
 [   0    0    0  443 6832 9112 3877 1533]
 [   0    0    0 5710 1107 3213 7443 2928]
 [   0    0    0    0 6988 6347 6825 3877]]


In [28]:
dim=10

In [30]:
model = Sequential()
model.add(Embedding(vocb_size,10,input_length=sent_height))
model.compile('adam','mse')

In [31]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________
